// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xruccxglwnximvgkfsrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhydWNjeGdsd254aW12Z2tmc3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzI3NzgsImV4cCI6MjA1NDk0ODc3OH0.hhU1I3W50OC0gyk6vUuLzcKsYHLBH1BtKBIPB_ubig8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);